### PR TITLE
Test get_grid_data

### PR DESCRIPTION
**Pull request by FancyBirb**
The Test should work, but my main issue with this and future pull requests is that i create all of my branches from my main branch, thus also always pulling other features that are not ready or don't belonge to the main idea of this branch. For example, the commit [added function wrappers for gradient8 and a small help page to use gr…](https://github.com/TopoToolbox/topotoolboxr/commit/fe6b58ef5c664711db87743a6e76cfdd59134292) is in here.

How can i fix this without distroying my main branch, when i merge the feature into it? 
- I head this problem with the "my-single-change" branch, and it screwed me a little bit. I always had to change stuff twice.

### CODE REVIEW

**Comment by wkearn** [comment]
> The Test should work,

Excellent! I will look over this today. 

> but my main issue with this and future pull requests is that i create all of my branches from my main branch, thus also always pulling other features that are not ready or don't belonge to the main idea of this branch. For example, the commit [added function wrappers for gradient8 and a small help page to use gr…](https://github.com/TopoToolbox/topotoolboxr/commit/fe6b58ef5c664711db87743a6e76cfdd59134292) is in here.
> 
> How can i fix this without distroying my main branch, when i merge the feature into it?
> 
>     * I head this problem with the "my-single-change" branch, and it screwed me a little bit. I always had to change stuff twice.

Figuring out a git workflow that works for you can be very challenging, but it is important. What works for me may not be the best thing for you. You'll have to do some experimentation to discover your personal preferences, but here is more or less how I work on TopoToolbox with git:

My local `main` branch on my computer tracks TopoToolbox/topotoolboxr `main`: I always keep it up to date whenever a pull request is merged by checking out `main` (`git switch main`) and pulling `git pull upstream main`. I never make changes on `main`, so this should always work to keep `main` up to date.

When I want to make a change, I create a new branch from `main` (`git branch new-feature-branch main`) and switch to it (`git switch new-feature-branch`).

Now I make changes and commit them to this branch with the usual sequence of `git add ...`, `git commit`.


If other changes have landed in `main` since I began working on `new-feature-branch`, I first update my local `main` branch as in 1., and then I *rebase* `new-feature-branch` onto the new changes by switching to `new-feature-branch` and running `git rebase main`. 

Rebasing [can be very confusing](https://jvns.ca/blog/2023/11/06/rebasing-what-can-go-wrong-/), and you could also merge `main` into `new-feature-branch`. They lead to more or less the same outcome: `new-feature-branch` has the code from the changes to `main`.

Whether you rebase or merge `main` into `new-feature-branch`, you might have merge conflicts. Fixing merge conflicts can be scary because git adds stuff that looks like

```C
<<<<<<< new-feature-branch
// Added `queue` array for a priority queue
void function1(float *dem, ptrdiff_t *queue, ptrdiff_t dims[2]) {
  // A bunch of new code that uses `queue`
}
=======
// Someone else added the `flats` array
void function1(float *dem, int32_t *flats, ptrdiff_t dims[2]) {
  // Some code that uses `flats`
}
>>>>>>> main
```

Your goal is to edit this file so that it looks like what you want it to including the changes from `main`. You should delete the `<<<<<<<`, `=======` and `>>>>>>>` lines and edit the code. This might be as simple as

```C
void function1(float *dem, int32_t *flats, ptrdiff_t *queue, ptrdiff_t dims[2]) {
  // Some code that uses `flats`

  // A bunch of new code that uses `queue`
}
```

Of course it may be more complicated. But your goal is always to leave the conflicted file in a state that incorporates all of the changes you want to make, including the changes someone else may have made in `main`. This is why small, focused pull requests are better than big ones: it makes merge conflicts less likely.

Once you resolve the merge conflict, use `git add` and `git commit` to continue the merge and resolve any remaining conflicts.

When you are finished with your change, push `new-feature-branch` to your fork. I have my remotes set up like this:

```
$ git remote -v
origin  git@github.com:wkearn/topotoolboxr (fetch)
origin  git@github.com:wkearn/topotoolboxr (push)
upstream        git@github.com:TopoToolbox/topotoolboxr (fetch)
upstream        git@github.com:TopoToolbox/topotoolboxr (push)
```

**Comment by wkearn** [comment]
I accidentally hit the close button. Sorry about that.

**Comment by FancyBirb** [comment]
This should be done, but gradient8 test is still missing. I will create another pull request for that

**Comment by FancyBirb** [comment]
Oh i closed this branch accidentally when i treid to rename my branch to make it less confusing

**Review by wkearn — CHANGES_REQUESTED** [review]
Looks pretty good, @FancyBirb!

There is one more minor thing we need to do: the `expect_no_message` and `expect_no_error` appear to have been added to `testthat` in v3.1.5. My previously installed testthat version happened to be 3.1.2, so the tests failed until I upgraded that. We should make this requirement clear by changing the required version number in DESCRIPTION:

```diff
--- a/DESCRIPTION
+++ b/DESCRIPTION
@@ -13,5 +13,5 @@ LazyData: true
 URL: https://github.com/TopoToolbox/topotoolboxr, https://github.com/TopoToolbox
 RoxygenNote: 7.3.1
 Suggests:
-    testthat (>= 3.0.0)
+    testthat (>= 3.1.5)
 Config/testthat/edition: 3
```

**Comment by FancyBirb** [comment]
Should be now mergeable

**Review by wkearn — APPROVED** [review]

**Pull request merged**
